// constants/ads.ts
import type { Ad } from '~/types/ad'; // Import the Ad type

export const latestAds: Ad[] = [
  {
    id: '1',
    title: 'Toyota Corolla 2018 Model',
    price: 'ETB 1,200,000',
    location: 'Addis Ababa',
    category: 'Vehicles',
    imageUrl: 'https://via.placeholder.com/400x300/a3e635/FFFFFF?text=Car',
    createdAt: '2 hours ago',
  },
  {
    id: '2',
    title: 'Apartment for Rent in Bole',
    price: 'ETB 30,000/month',
    location: 'Addis Ababa',
    category: 'Real Estate',
    imageUrl: 'https://via.placeholder.com/400x300/fde047/FFFFFF?text=Apartment',
    createdAt: '5 hours ago',
  },
  {
    id: '3',
    title: 'iPhone 13 Pro Max (Used)',
    price: 'ETB 45,000',
    location: 'Bahir Dar',
    category: 'Electronics',
    imageUrl: 'https://via.placeholder.com/400x300/a78bfa/FFFFFF?text=Phone',
    createdAt: '1 day ago',
  },
  {
    id: '4',
    title: 'Samsung Smart TV 55-inch',
    price: 'ETB 25,000',
    location: 'Gondar',
    category: 'Electronics',
    imageUrl: 'https://via.placeholder.com/400x300/fbbf24/FFFFFF?text=TV',
    createdAt: '1 day ago',
  },
  {
    id: '5',
    title: 'Job: Software Developer',
    price: 'Negotiable',
    location: 'Remote',
    category: 'Jobs',
    imageUrl: 'https://via.placeholder.com/400x300/67e8f9/FFFFFF?text=Job',
    createdAt: '2 days ago',
  },
  {
    id: '6',
    title: 'Modern Sofa Set',
    price: 'ETB 60,000',
    location: 'Addis Ababa',
    category: 'Home Appliances',
    imageUrl: 'https://via.placeholder.com/400x300/d8b4fe/FFFFFF?text=Sofa',
    createdAt: '3 days ago',
  },
  {
    id: '7',
    title: 'Hiking Boots (Size 42)',
    price: 'ETB 3,500',
    location: 'Adama',
    category: 'Fashion',
    imageUrl: 'https://via.placeholder.com/400x300/fbcfe8/FFFFFF?text=Boots',
    createdAt: '4 days ago',
  },
  {
    id: '8',
    title: 'Professional Photography Service',
    price: 'Custom Quote',
    location: 'Nationwide',
    category: 'Services',
    imageUrl: 'https://via.placeholder.com/400x300/fda47a/FFFFFF?text=Service',
    createdAt: '5 days ago',
  },
];